#include "codegen_c.h"
#include "../tree/type.h"
#include <iostream>
#include <fstream>
#include <cstdlib>

Codegen_C::Codegen_C(bool debug) : debug(debug), indentLevel(0), stringCounter(0), tempCounter(0), labelCounter(0) {
    current = &mainCode;

    // Emit standard header
    header << "/* Generated by Rufio C Backend */\n";
    header << "#include <stdint.h>\n";
    header << "#include <stdlib.h>\n";
    header << "#include <string.h>\n";
    header << "#include <math.h>\n";
    header << "\n";
    header << "/* Blitz3D Runtime types */\n";
    header << "typedef int64_t bb_int_t;\n";
    header << "typedef double bb_float_t;\n";
    header << "typedef char* bb_string_t;\n";
    header << "typedef void* bb_obj_t;\n";
    header << "\n";
    header << "/* Type metadata - must match runtime's blitz.h */\n";
    header << "typedef struct BBType { bb_int_t type; } BBType;\n";
    header << "typedef union BBField { bb_int_t INT; bb_float_t FLT; void *STR; char *CSTR; void *OBJ; void *VEC; } BBField;\n";
    header << "typedef struct BBObj { BBField *fields; struct BBObj *next, *prev; void *type; bb_int_t ref_cnt; } BBObj;\n";
    header << "typedef struct BBObjType { bb_int_t type; BBObj used, free; bb_int_t fieldCnt; BBType *fieldTypes[1]; } BBObjType;\n";
    header << "typedef struct BBVecType { BBType base; bb_int_t size; BBType *elementType; } BBVecType;\n";
    header << "typedef struct BBArray { void *data; bb_int_t elementType; bb_int_t dims; bb_int_t scales[1]; } BBArray;\n";
    header << "extern BBType _bbIntType, _bbFltType, _bbStrType;\n";
    header << "\n";
    header << "/* Runtime function declarations */\n";
    header << "extern int bbStart(int argc, char **argv, void (*main)(void), int debug);\n";
    header << "extern void _bbRestore(bb_int_t *data);\n";
    header << "extern void __bbLoadLibs(void *libs);\n";
    header << "extern bb_string_t _bbStrConst(const char *s);\n";
    header << "extern void _bbStrRelease(bb_string_t s);\n";
    header << "extern bb_string_t bbStr(bb_int_t n);\n";
    header << "extern bb_string_t bbStrFloat(bb_float_t n);\n";
    header << "extern void bbPrint(bb_string_t s);\n";
    header << "extern void bbEnd(void);\n";
    header << "extern void _bbPushGosub(void *addr);\n";
    header << "extern void *_bbPopGosub(void);\n";
    header << "extern bb_int_t bbMilliSecs(void);\n";
    header << "extern bb_float_t bbSin(bb_float_t n);\n";
    header << "extern bb_float_t bbCos(bb_float_t n);\n";
    header << "extern bb_float_t bbFloat(bb_int_t n);\n";
    header << "extern bb_int_t bbInt(bb_float_t n);\n";
    header << "extern bb_int_t bbLen(bb_string_t s);\n";
    header << "extern bb_string_t bbConcat(bb_string_t a, bb_string_t b);\n";
    header << "extern bb_int_t bbMod(bb_int_t a, bb_int_t b);\n";
    header << "extern bb_int_t _bbMod(bb_int_t a, bb_int_t b);\n";
    header << "extern bb_float_t _bbFMod(bb_float_t a, bb_float_t b);\n";
    header << "extern bb_float_t _bbFPow(bb_float_t a, bb_float_t b);\n";
    header << "extern bb_string_t _bbStrFromInt(bb_int_t n);\n";
    header << "extern bb_string_t _bbStrFromFloat(bb_float_t n);\n";
    header << "extern bb_string_t _bbStrConcat(bb_string_t a, bb_string_t b);\n";
    header << "extern bb_int_t _bbStrCompare(bb_string_t a, bb_string_t b);\n";
    header << "extern bb_string_t _bbStrLoad(bb_string_t *s);\n";
    header << "extern bb_string_t _bbStrCopy(bb_string_t s);\n";
    header << "extern void _bbStrStore(bb_string_t *s, bb_string_t v);\n";
    header << "extern void _bbObjStore(void **p, bb_obj_t o);\n";
    header << "\n";
    header << "/* Object runtime functions */\n";
    header << "extern bb_obj_t _bbObjNew(BBObjType *type);\n";
    header << "extern void _bbObjDelete(bb_obj_t obj);\n";
    header << "extern void _bbObjDeleteEach(BBObjType *type);\n";
    header << "extern bb_int_t _bbObjEachFirst(bb_obj_t *var, BBObjType *type);\n";
    header << "extern bb_int_t _bbObjEachNext(bb_obj_t *var);\n";
    header << "extern bb_int_t _bbObjEachFirst2(bb_obj_t *var, BBObjType *type);\n";
    header << "extern bb_int_t _bbObjEachNext2(bb_obj_t *var);\n";
    header << "extern bb_obj_t _bbObjFirst(BBObjType *type);\n";
    header << "extern bb_obj_t _bbObjLast(BBObjType *type);\n";
    header << "extern bb_obj_t _bbObjNext(bb_obj_t obj);\n";
    header << "extern bb_obj_t _bbObjPrev(bb_obj_t obj);\n";
    header << "extern void _bbObjInsBefore(bb_obj_t o1, bb_obj_t o2);\n";
    header << "extern void _bbObjInsAfter(bb_obj_t o1, bb_obj_t o2);\n";
    header << "extern bb_int_t _bbObjCompare(bb_obj_t a, bb_obj_t b);\n";
    header << "extern bb_obj_t _bbObjLoad(bb_obj_t *p);\n";
    header << "extern bb_int_t _bbObjHandle(bb_obj_t obj);\n";
    header << "extern bb_obj_t _bbObjFromHandle(bb_int_t handle, BBObjType *type);\n";
    header << "\n";
    header << "/* Vector functions */\n";
    header << "extern void *_bbVecAlloc(BBVecType *type);\n";
    header << "extern void _bbVecFree(void *vec, BBVecType *type);\n";
    header << "\n";
    header << "/* Array functions */\n";
    header << "extern void _bbUndimArray(BBArray *arr);\n";
    header << "extern void _bbDimArray(BBArray *arr);\n";
    header << "\n";
    header << "/* String functions */\n";
    header << "extern bb_string_t bbTrim(bb_string_t s);\n";
    header << "extern bb_string_t bbMid(bb_string_t s, bb_int_t start, bb_int_t len);\n";
    header << "extern bb_string_t bbLeft(bb_string_t s, bb_int_t n);\n";
    header << "extern bb_string_t bbRight(bb_string_t s, bb_int_t n);\n";
    header << "extern bb_string_t bbReplace(bb_string_t s, bb_string_t find, bb_string_t replace);\n";
    header << "extern bb_string_t bbLower(bb_string_t s);\n";
    header << "extern bb_string_t bbUpper(bb_string_t s);\n";
    header << "extern bb_int_t bbInstr(bb_string_t s, bb_string_t find, bb_int_t start);\n";
    header << "extern bb_int_t bbAsc(bb_string_t s);\n";
    header << "extern bb_string_t bbChr(bb_int_t n);\n";
    header << "extern bb_string_t bbString(bb_string_t s, bb_int_t n);\n";
    header << "extern bb_float_t _bbStrToFloat(bb_string_t s);\n";
    header << "\n";
    header << "/* File I/O */\n";
    header << "extern bb_int_t bbReadFile(bb_string_t filename);\n";
    header << "extern bb_int_t bbWriteFile(bb_string_t filename);\n";
    header << "extern bb_string_t bbReadLine(bb_int_t handle);\n";
    header << "extern void bbWriteLine(bb_int_t handle, bb_string_t line);\n";
    header << "extern void bbCloseFile(bb_int_t handle);\n";
    header << "extern bb_int_t bbEof(bb_int_t handle);\n";
    header << "extern bb_int_t bbFileType(bb_string_t file);\n";
    header << "extern void bbDeleteFile(bb_string_t file);\n";
    header << "extern bb_int_t bbReadDir(bb_string_t dir);\n";
    header << "extern bb_string_t bbNextFile(bb_int_t handle);\n";
    header << "extern void bbCloseDir(bb_int_t handle);\n";
    header << "\n";
    header << "/* System functions */\n";
    header << "extern void bbDelay(bb_int_t ms);\n";
    header << "extern void bbWaitKey(void);\n";
    header << "extern bb_float_t bbSqr(bb_float_t n);\n";
    header << "extern bb_float_t bbAbs(bb_float_t n);\n";
    header << "extern bb_float_t bbTan(bb_float_t n);\n";
    header << "extern bb_float_t bbASin(bb_float_t n);\n";
    header << "extern bb_float_t bbACos(bb_float_t n);\n";
    header << "extern bb_float_t bbATan(bb_float_t n);\n";
    header << "extern bb_float_t bbATan2(bb_float_t y, bb_float_t x);\n";
    header << "extern bb_float_t bbLog(bb_float_t n);\n";
    header << "extern bb_float_t bbLog10(bb_float_t n);\n";
    header << "extern bb_float_t bbExp(bb_float_t n);\n";
    header << "extern bb_float_t bbCeil(bb_float_t n);\n";
    header << "extern bb_float_t bbFloor(bb_float_t n);\n";
    header << "extern bb_int_t bbRand(bb_int_t from, bb_int_t to);\n";
    header << "extern bb_float_t bbRnd(bb_float_t from, bb_float_t to);\n";
    header << "extern void bbSeedRnd(bb_int_t seed);\n";
    header << "\n";
    header << "/* Graphics functions */\n";
    header << "extern bb_int_t bbCountGfxDrivers(void);\n";
    header << "extern bb_string_t bbGfxDriverName(bb_int_t driver);\n";
    header << "extern void bbSetGfxDriver(bb_int_t driver);\n";
    header << "extern bb_int_t bbCountGfxModes(void);\n";
    header << "extern bb_int_t bbGfxMode3D(bb_int_t mode);\n";
    header << "extern bb_int_t bbGfxMode3DExists(bb_int_t w, bb_int_t h, bb_int_t d);\n";
    header << "extern void bbGraphics(bb_int_t w, bb_int_t h, bb_int_t d, bb_int_t mode);\n";
    header << "extern void bbGraphics3D(bb_int_t w, bb_int_t h, bb_int_t d, bb_int_t mode);\n";
    header << "extern void bbHWMultiTex(bb_int_t enable);\n";
    header << "extern void bbSetBuffer(bb_int_t buffer);\n";
    header << "extern bb_int_t bbBackBuffer(void);\n";
    header << "extern bb_int_t bbFrontBuffer(void);\n";
    header << "extern void bbFlip(bb_int_t sync);\n";
    header << "extern void bbCls(void);\n";
    header << "extern void bbClsColor(bb_int_t r, bb_int_t g, bb_int_t b);\n";
    header << "extern void bbColor(bb_int_t r, bb_int_t g, bb_int_t b);\n";
    header << "extern void bbRect(bb_int_t x, bb_int_t y, bb_int_t w, bb_int_t h, bb_int_t solid);\n";
    header << "extern void bbOval(bb_int_t x, bb_int_t y, bb_int_t w, bb_int_t h, bb_int_t solid);\n";
    header << "extern void bbLine(bb_int_t x1, bb_int_t y1, bb_int_t x2, bb_int_t y2);\n";
    header << "extern void bbPlot(bb_int_t x, bb_int_t y);\n";
    header << "extern void bbText(bb_int_t x, bb_int_t y, bb_string_t text, bb_int_t cx, bb_int_t cy);\n";
    header << "extern void bbLocate(bb_int_t x, bb_int_t y);\n";
    header << "extern bb_int_t bbGraphicsWidth(void);\n";
    header << "extern bb_int_t bbGraphicsHeight(void);\n";
    header << "extern bb_int_t bbGraphicsDepth(void);\n";
    header << "extern void bbOrigin(bb_int_t x, bb_int_t y);\n";
    header << "extern void bbViewport(bb_int_t x, bb_int_t y, bb_int_t w, bb_int_t h);\n";
    header << "extern bb_int_t bbLoadImage(bb_string_t file);\n";
    header << "extern bb_int_t bbLoadAnimImage(bb_string_t file, bb_int_t w, bb_int_t h, bb_int_t first, bb_int_t count);\n";
    header << "extern void bbDrawImage(bb_int_t image, bb_int_t x, bb_int_t y, bb_int_t frame);\n";
    header << "extern void bbFreeImage(bb_int_t image);\n";
    header << "extern bb_int_t bbImageWidth(bb_int_t image);\n";
    header << "extern bb_int_t bbImageHeight(bb_int_t image);\n";
    header << "extern void bbMaskImage(bb_int_t image, bb_int_t r, bb_int_t g, bb_int_t b);\n";
    header << "extern bb_int_t bbCreateImage(bb_int_t w, bb_int_t h, bb_int_t frames);\n";
    header << "extern void bbGrabImage(bb_int_t image, bb_int_t x, bb_int_t y, bb_int_t frame);\n";
    header << "extern bb_int_t bbSaveImage(bb_int_t image, bb_string_t filename, bb_int_t frame);\n";
    header << "extern bb_int_t bbLoadFont(bb_string_t name, bb_int_t height, bb_int_t bold, bb_int_t italic, bb_int_t underline);\n";
    header << "extern void bbSetFont(bb_int_t font);\n";
    header << "extern void bbFreeFont(bb_int_t font);\n";
    header << "extern bb_int_t bbStringWidth(bb_string_t s);\n";
    header << "extern bb_int_t bbStringHeight(bb_string_t s);\n";
    header << "extern void bbAppTitle(bb_string_t title, bb_string_t close);\n";
    header << "extern void bbLockBuffer(bb_int_t buffer);\n";
    header << "extern void bbUnlockBuffer(bb_int_t buffer);\n";
    header << "extern bb_int_t bbReadPixelFast(bb_int_t x, bb_int_t y, bb_int_t buffer);\n";
    header << "extern void bbWritePixelFast(bb_int_t x, bb_int_t y, bb_int_t argb, bb_int_t buffer);\n";
    header << "extern bb_int_t bbReadPixel(bb_int_t x, bb_int_t y, bb_int_t buffer);\n";
    header << "extern void bbWritePixel(bb_int_t x, bb_int_t y, bb_int_t argb, bb_int_t buffer);\n";
    header << "extern void bbCopyPixel(bb_int_t sx, bb_int_t sy, bb_int_t src, bb_int_t dx, bb_int_t dy, bb_int_t dst);\n";
    header << "extern void bbCopyPixelFast(bb_int_t sx, bb_int_t sy, bb_int_t src, bb_int_t dx, bb_int_t dy, bb_int_t dst);\n";
    header << "\n";
    header << "/* Input functions */\n";
    header << "extern bb_int_t bbKeyDown(bb_int_t key);\n";
    header << "extern bb_int_t bbKeyHit(bb_int_t key);\n";
    header << "extern bb_int_t bbGetKey(bb_int_t ascii);\n";
    header << "extern void bbFlushKeys(void);\n";
    header << "extern bb_int_t bbMouseDown(bb_int_t button);\n";
    header << "extern bb_int_t bbMouseHit(bb_int_t button);\n";
    header << "extern bb_int_t bbMouseX(void);\n";
    header << "extern bb_int_t bbMouseY(void);\n";
    header << "extern bb_int_t bbMouseZ(void);\n";
    header << "extern bb_int_t bbMouseXSpeed(void);\n";
    header << "extern bb_int_t bbMouseYSpeed(void);\n";
    header << "extern bb_int_t bbMouseZSpeed(void);\n";
    header << "extern void bbMoveMouse(bb_int_t x, bb_int_t y);\n";
    header << "extern void bbFlushMouse(void);\n";
    header << "extern void bbHidePointer(void);\n";
    header << "extern void bbShowPointer(void);\n";
    header << "\n";
    header << "/* 3D Graphics functions */\n";
    header << "extern bb_int_t bbCreateCamera(bb_int_t parent);\n";
    header << "extern bb_int_t bbCreateLight(bb_int_t type, bb_int_t parent);\n";
    header << "extern bb_int_t bbCreatePivot(bb_int_t parent);\n";
    header << "extern bb_int_t bbCreateCube(bb_int_t parent);\n";
    header << "extern bb_int_t bbCreateSphere(bb_int_t segs, bb_int_t parent);\n";
    header << "extern bb_int_t bbCreateCylinder(bb_int_t segs, bb_int_t solid, bb_int_t parent);\n";
    header << "extern bb_int_t bbCreateCone(bb_int_t segs, bb_int_t solid, bb_int_t parent);\n";
    header << "extern bb_int_t bbCreatePlane(bb_int_t segs, bb_int_t parent);\n";
    header << "extern bb_int_t bbCreateMesh(bb_int_t parent);\n";
    header << "extern bb_int_t bbLoadMesh(bb_string_t file, bb_int_t parent);\n";
    header << "extern bb_int_t bbLoadAnimMesh(bb_string_t file, bb_int_t parent);\n";
    header << "extern bb_int_t bbCopyMesh(bb_int_t mesh, bb_int_t parent);\n";
    header << "extern void bbFreeEntity(bb_int_t entity);\n";
    header << "extern void bbPositionEntity(bb_int_t entity, bb_float_t x, bb_float_t y, bb_float_t z, bb_int_t global);\n";
    header << "extern void bbMoveEntity(bb_int_t entity, bb_float_t x, bb_float_t y, bb_float_t z);\n";
    header << "extern void bbTranslateEntity(bb_int_t entity, bb_float_t x, bb_float_t y, bb_float_t z, bb_int_t global);\n";
    header << "extern void bbRotateEntity(bb_int_t entity, bb_float_t pitch, bb_float_t yaw, bb_float_t roll, bb_int_t global);\n";
    header << "extern void bbTurnEntity(bb_int_t entity, bb_float_t pitch, bb_float_t yaw, bb_float_t roll, bb_int_t global);\n";
    header << "extern void bbScaleEntity(bb_int_t entity, bb_float_t x, bb_float_t y, bb_float_t z, bb_int_t global);\n";
    header << "extern void bbPointEntity(bb_int_t src, bb_int_t dest, bb_float_t roll);\n";
    header << "extern void bbAlignToVector(bb_int_t entity, bb_float_t vx, bb_float_t vy, bb_float_t vz, bb_int_t axis, bb_float_t rate);\n";
    header << "extern bb_float_t bbEntityX(bb_int_t entity, bb_int_t global);\n";
    header << "extern bb_float_t bbEntityY(bb_int_t entity, bb_int_t global);\n";
    header << "extern bb_float_t bbEntityZ(bb_int_t entity, bb_int_t global);\n";
    header << "extern bb_float_t bbEntityPitch(bb_int_t entity, bb_int_t global);\n";
    header << "extern bb_float_t bbEntityYaw(bb_int_t entity, bb_int_t global);\n";
    header << "extern bb_float_t bbEntityRoll(bb_int_t entity, bb_int_t global);\n";
    header << "extern void bbShowEntity(bb_int_t entity);\n";
    header << "extern void bbHideEntity(bb_int_t entity);\n";
    header << "extern void bbEntityColor(bb_int_t entity, bb_float_t r, bb_float_t g, bb_float_t b);\n";
    header << "extern void bbEntityAlpha(bb_int_t entity, bb_float_t alpha);\n";
    header << "extern void bbEntityTexture(bb_int_t entity, bb_int_t texture, bb_int_t frame, bb_int_t index);\n";
    header << "extern void bbEntityParent(bb_int_t entity, bb_int_t parent, bb_int_t global);\n";
    header << "extern bb_int_t bbGetParent(bb_int_t entity);\n";
    header << "extern bb_int_t bbCountChildren(bb_int_t entity);\n";
    header << "extern bb_int_t bbGetChild(bb_int_t entity, bb_int_t index);\n";
    header << "extern bb_int_t bbFindChild(bb_int_t entity, bb_string_t name);\n";
    header << "extern void bbNameEntity(bb_int_t entity, bb_string_t name);\n";
    header << "extern bb_string_t bbEntityName(bb_int_t entity);\n";
    header << "extern void bbEntityOrder(bb_int_t entity, bb_int_t order);\n";
    header << "extern void bbEntityAutoFade(bb_int_t entity, bb_float_t near, bb_float_t far);\n";
    header << "extern bb_int_t bbLoadTexture(bb_string_t file, bb_int_t flags);\n";
    header << "extern bb_int_t bbLoadAnimTexture(bb_string_t file, bb_int_t flags, bb_int_t w, bb_int_t h, bb_int_t first, bb_int_t count);\n";
    header << "extern bb_int_t bbCreateTexture(bb_int_t w, bb_int_t h, bb_int_t flags, bb_int_t frames);\n";
    header << "extern void bbFreeTexture(bb_int_t texture);\n";
    header << "extern void bbScaleTexture(bb_int_t texture, bb_float_t u, bb_float_t v);\n";
    header << "extern void bbPositionTexture(bb_int_t texture, bb_float_t u, bb_float_t v);\n";
    header << "extern void bbRotateTexture(bb_int_t texture, bb_float_t angle);\n";
    header << "extern bb_int_t bbTextureWidth(bb_int_t texture);\n";
    header << "extern bb_int_t bbTextureHeight(bb_int_t texture);\n";
    header << "extern bb_int_t bbTextureBuffer(bb_int_t texture, bb_int_t frame);\n";
    header << "extern void bbTextureBlend(bb_int_t texture, bb_int_t blend);\n";
    header << "extern void bbClearTextureFilters(void);\n";
    header << "extern void bbRenderWorld(bb_float_t tween);\n";
    header << "extern void bbUpdateWorld(bb_float_t elapsed);\n";
    header << "extern void bbCameraViewport(bb_int_t camera, bb_int_t x, bb_int_t y, bb_int_t w, bb_int_t h);\n";
    header << "extern void bbCameraClsColor(bb_int_t camera, bb_float_t r, bb_float_t g, bb_float_t b);\n";
    header << "extern void bbCameraRange(bb_int_t camera, bb_float_t near, bb_float_t far);\n";
    header << "extern void bbCameraZoom(bb_int_t camera, bb_float_t zoom);\n";
    header << "extern void bbCameraFogMode(bb_int_t camera, bb_int_t mode);\n";
    header << "extern void bbCameraFogColor(bb_int_t camera, bb_float_t r, bb_float_t g, bb_float_t b);\n";
    header << "extern void bbCameraFogRange(bb_int_t camera, bb_float_t near, bb_float_t far);\n";
    header << "extern void bbCameraClsMode(bb_int_t camera, bb_int_t clsColor, bb_int_t clsZ);\n";
    header << "extern void bbCameraProjMode(bb_int_t camera, bb_int_t mode);\n";
    header << "extern bb_int_t bbCameraProject(bb_int_t camera, bb_float_t x, bb_float_t y, bb_float_t z);\n";
    header << "extern bb_float_t bbProjectedX(void);\n";
    header << "extern bb_float_t bbProjectedY(void);\n";
    header << "extern bb_float_t bbProjectedZ(void);\n";
    header << "extern void bbLightColor(bb_int_t light, bb_float_t r, bb_float_t g, bb_float_t b);\n";
    header << "extern void bbLightRange(bb_int_t light, bb_float_t range);\n";
    header << "extern void bbLightConeAngles(bb_int_t light, bb_float_t inner, bb_float_t outer);\n";
    header << "extern void bbAmbientLight(bb_float_t r, bb_float_t g, bb_float_t b);\n";
    header << "extern bb_int_t bbCreateSprite(bb_int_t parent);\n";
    header << "extern bb_int_t bbLoadSprite(bb_string_t file, bb_int_t flags, bb_int_t parent);\n";
    header << "extern void bbSpriteViewMode(bb_int_t sprite, bb_int_t mode);\n";
    header << "extern void bbHandleSprite(bb_int_t sprite, bb_float_t x, bb_float_t y);\n";
    header << "extern void bbScaleSprite(bb_int_t sprite, bb_float_t x, bb_float_t y);\n";
    header << "extern void bbRotateSprite(bb_int_t sprite, bb_float_t angle);\n";
    header << "extern bb_int_t bbEntityCollided(bb_int_t entity, bb_int_t type);\n";
    header << "extern bb_int_t bbCountCollisions(bb_int_t entity);\n";
    header << "extern bb_float_t bbCollisionX(bb_int_t entity, bb_int_t index);\n";
    header << "extern bb_float_t bbCollisionY(bb_int_t entity, bb_int_t index);\n";
    header << "extern bb_float_t bbCollisionZ(bb_int_t entity, bb_int_t index);\n";
    header << "extern bb_float_t bbCollisionNX(bb_int_t entity, bb_int_t index);\n";
    header << "extern bb_float_t bbCollisionNY(bb_int_t entity, bb_int_t index);\n";
    header << "extern bb_float_t bbCollisionNZ(bb_int_t entity, bb_int_t index);\n";
    header << "extern bb_int_t bbCollisionEntity(bb_int_t entity, bb_int_t index);\n";
    header << "extern bb_int_t bbCollisionSurface(bb_int_t entity, bb_int_t index);\n";
    header << "extern bb_int_t bbCollisionTriangle(bb_int_t entity, bb_int_t index);\n";
    header << "extern void bbEntityType(bb_int_t entity, bb_int_t collType, bb_int_t recursive);\n";
    header << "extern void bbEntityRadius(bb_int_t entity, bb_float_t rx, bb_float_t ry);\n";
    header << "extern void bbEntityBox(bb_int_t entity, bb_float_t x, bb_float_t y, bb_float_t z, bb_float_t w, bb_float_t h, bb_float_t d);\n";
    header << "extern void bbCollisions(bb_int_t srcType, bb_int_t destType, bb_int_t method, bb_int_t response);\n";
    header << "extern void bbResetEntity(bb_int_t entity);\n";
    header << "extern void bbEntityPickMode(bb_int_t entity, bb_int_t mode, bb_int_t obscurer);\n";
    header << "extern bb_int_t bbCameraPick(bb_int_t camera, bb_float_t x, bb_float_t y);\n";
    header << "extern bb_int_t bbLinePick(bb_float_t x, bb_float_t y, bb_float_t z, bb_float_t dx, bb_float_t dy, bb_float_t dz, bb_float_t radius);\n";
    header << "extern bb_int_t bbEntityPick(bb_int_t entity, bb_float_t range);\n";
    header << "extern bb_float_t bbPickedX(void);\n";
    header << "extern bb_float_t bbPickedY(void);\n";
    header << "extern bb_float_t bbPickedZ(void);\n";
    header << "extern bb_float_t bbPickedNX(void);\n";
    header << "extern bb_float_t bbPickedNY(void);\n";
    header << "extern bb_float_t bbPickedNZ(void);\n";
    header << "extern bb_int_t bbPickedEntity(void);\n";
    header << "extern bb_int_t bbPickedSurface(void);\n";
    header << "extern bb_int_t bbPickedTriangle(void);\n";
    header << "extern bb_float_t bbEntityDistance(bb_int_t src, bb_int_t dest);\n";
    header << "extern bb_int_t bbDeltaYaw(bb_int_t src, bb_int_t dest);\n";
    header << "extern bb_int_t bbDeltaPitch(bb_int_t src, bb_int_t dest);\n";
    header << "extern bb_float_t bbTFormedX(void);\n";
    header << "extern bb_float_t bbTFormedY(void);\n";
    header << "extern bb_float_t bbTFormedZ(void);\n";
    header << "extern void bbTFormPoint(bb_float_t x, bb_float_t y, bb_float_t z, bb_int_t src, bb_int_t dest);\n";
    header << "extern void bbTFormVector(bb_float_t x, bb_float_t y, bb_float_t z, bb_int_t src, bb_int_t dest);\n";
    header << "extern void bbTFormNormal(bb_float_t x, bb_float_t y, bb_float_t z, bb_int_t src, bb_int_t dest);\n";
    header << "extern bb_int_t bbAddSurface(bb_int_t mesh);\n";
    header << "extern bb_int_t bbAddVertex(bb_int_t surface, bb_float_t x, bb_float_t y, bb_float_t z, bb_float_t u, bb_float_t v, bb_float_t w);\n";
    header << "extern void bbAddTriangle(bb_int_t surface, bb_int_t v0, bb_int_t v1, bb_int_t v2);\n";
    header << "extern void bbVertexCoords(bb_int_t surface, bb_int_t index, bb_float_t x, bb_float_t y, bb_float_t z);\n";
    header << "extern void bbVertexColor(bb_int_t surface, bb_int_t index, bb_float_t r, bb_float_t g, bb_float_t b, bb_float_t a);\n";
    header << "extern void bbVertexNormal(bb_int_t surface, bb_int_t index, bb_float_t nx, bb_float_t ny, bb_float_t nz);\n";
    header << "extern void bbVertexTexCoords(bb_int_t surface, bb_int_t index, bb_float_t u, bb_float_t v, bb_float_t w, bb_int_t set);\n";
    header << "extern bb_int_t bbCountSurfaces(bb_int_t mesh);\n";
    header << "extern bb_int_t bbGetSurface(bb_int_t mesh, bb_int_t index);\n";
    header << "extern bb_int_t bbCountVertices(bb_int_t surface);\n";
    header << "extern bb_int_t bbCountTriangles(bb_int_t surface);\n";
    header << "extern bb_float_t bbVertexX(bb_int_t surface, bb_int_t index);\n";
    header << "extern bb_float_t bbVertexY(bb_int_t surface, bb_int_t index);\n";
    header << "extern bb_float_t bbVertexZ(bb_int_t surface, bb_int_t index);\n";
    header << "extern bb_float_t bbVertexNX(bb_int_t surface, bb_int_t index);\n";
    header << "extern bb_float_t bbVertexNY(bb_int_t surface, bb_int_t index);\n";
    header << "extern bb_float_t bbVertexNZ(bb_int_t surface, bb_int_t index);\n";
    header << "extern bb_float_t bbVertexU(bb_int_t surface, bb_int_t index, bb_int_t set);\n";
    header << "extern bb_float_t bbVertexV(bb_int_t surface, bb_int_t index, bb_int_t set);\n";
    header << "extern bb_int_t bbTriangleVertex(bb_int_t surface, bb_int_t index, bb_int_t corner);\n";
    header << "extern void bbUpdateNormals(bb_int_t mesh);\n";
    header << "extern bb_int_t bbGetEntityBrush(bb_int_t entity);\n";
    header << "extern bb_int_t bbGetSurfaceBrush(bb_int_t surface);\n";
    header << "extern void bbPaintEntity(bb_int_t entity, bb_int_t brush);\n";
    header << "extern void bbPaintSurface(bb_int_t surface, bb_int_t brush);\n";
    header << "extern void bbPaintMesh(bb_int_t mesh, bb_int_t brush);\n";
    header << "extern bb_int_t bbCreateBrush(bb_float_t r, bb_float_t g, bb_float_t b);\n";
    header << "extern bb_int_t bbLoadBrush(bb_string_t file, bb_int_t flags, bb_float_t u, bb_float_t v);\n";
    header << "extern void bbFreeBrush(bb_int_t brush);\n";
    header << "extern void bbBrushColor(bb_int_t brush, bb_float_t r, bb_float_t g, bb_float_t b);\n";
    header << "extern void bbBrushAlpha(bb_int_t brush, bb_float_t alpha);\n";
    header << "extern void bbBrushShininess(bb_int_t brush, bb_float_t shine);\n";
    header << "extern void bbBrushTexture(bb_int_t brush, bb_int_t texture, bb_int_t frame, bb_int_t index);\n";
    header << "extern void bbBrushBlend(bb_int_t brush, bb_int_t blend);\n";
    header << "extern void bbBrushFX(bb_int_t brush, bb_int_t fx);\n";
    header << "extern void bbEntityFX(bb_int_t entity, bb_int_t fx);\n";
    header << "extern void bbEntityBlend(bb_int_t entity, bb_int_t blend);\n";
    header << "extern void bbEntityShininess(bb_int_t entity, bb_float_t shine);\n";
    header << "extern bb_int_t bbAnimating(bb_int_t entity);\n";
    header << "extern void bbAnimate(bb_int_t entity, bb_int_t mode, bb_float_t speed, bb_int_t seq, bb_float_t trans);\n";
    header << "extern void bbSetAnimKey(bb_int_t entity, bb_int_t frame, bb_int_t posKey, bb_int_t rotKey, bb_int_t scaleKey);\n";
    header << "extern bb_int_t bbExtractAnimSeq(bb_int_t entity, bb_int_t first, bb_int_t last, bb_int_t seq);\n";
    header << "extern bb_int_t bbAddAnimSeq(bb_int_t entity, bb_int_t length);\n";
    header << "extern void bbSetAnimTime(bb_int_t entity, bb_float_t time, bb_int_t seq);\n";
    header << "extern bb_int_t bbAnimSeq(bb_int_t entity);\n";
    header << "extern bb_float_t bbAnimTime(bb_int_t entity);\n";
    header << "extern bb_int_t bbAnimLength(bb_int_t entity);\n";
    header << "extern void bbWireFrame(bb_int_t enable);\n";
    header << "extern void bbDither(bb_int_t enable);\n";
    header << "extern void bbAntiAlias(bb_int_t enable);\n";
    header << "extern void bbClearWorld(bb_int_t entities, bb_int_t brushes, bb_int_t textures);\n";
    header << "\n";
    header << "/* Audio functions */\n";
    header << "extern bb_int_t bbLoadSound(bb_string_t file);\n";
    header << "extern void bbFreeSound(bb_int_t sound);\n";
    header << "extern bb_int_t bbPlaySound(bb_int_t sound);\n";
    header << "extern void bbLoopSound(bb_int_t sound);\n";
    header << "extern void bbSoundVolume(bb_int_t sound, bb_float_t volume);\n";
    header << "extern void bbSoundPitch(bb_int_t sound, bb_int_t pitch);\n";
    header << "extern void bbSoundPan(bb_int_t sound, bb_float_t pan);\n";
    header << "extern bb_int_t bbPlayMusic(bb_string_t file);\n";
    header << "extern void bbStopChannel(bb_int_t channel);\n";
    header << "extern void bbPauseChannel(bb_int_t channel);\n";
    header << "extern void bbResumeChannel(bb_int_t channel);\n";
    header << "extern void bbChannelVolume(bb_int_t channel, bb_float_t volume);\n";
    header << "extern void bbChannelPitch(bb_int_t channel, bb_int_t pitch);\n";
    header << "extern void bbChannelPan(bb_int_t channel, bb_float_t pan);\n";
    header << "extern bb_int_t bbChannelPlaying(bb_int_t channel);\n";
    header << "extern bb_int_t bbLoad3DSound(bb_string_t file);\n";
    header << "extern bb_int_t bbEmitSound(bb_int_t sound, bb_int_t entity);\n";
    header << "\n";
    header << "/* Additional graphics functions */\n";
    header << "extern bb_int_t bbCountGfxModes3D(void);\n";
    header << "extern bb_int_t bbWindowed3D(void);\n";
    header << "extern bb_int_t bbGfxModeWidth(bb_int_t mode);\n";
    header << "extern bb_int_t bbGfxModeHeight(bb_int_t mode);\n";
    header << "extern bb_int_t bbGfxModeDepth(bb_int_t mode);\n";
    header << "extern bb_int_t bbFontHeight(void);\n";
    header << "extern void bbMidHandle(bb_int_t image);\n";
    header << "extern void bbDrawBlock(bb_int_t image, bb_int_t x, bb_int_t y, bb_int_t frame);\n";
    header << "extern void bbRuntimeError(bb_string_t msg);\n";
    header << "extern void bbEndGraphics(void);\n";
    header << "extern bb_string_t bbCommandLine(void);\n";
    header << "extern bb_int_t bbExecFile(bb_string_t file);\n";
    header << "extern bb_int_t bbCopyEntity(bb_int_t entity, bb_int_t parent);\n";
    header << "extern bb_float_t bbTerrainHeight(bb_int_t terrain, bb_int_t x, bb_int_t z);\n";
    header << "extern bb_float_t bbTerrainY(bb_int_t terrain, bb_float_t x, bb_float_t y, bb_float_t z);\n";
    header << "extern void bbModifyTerrain(bb_int_t terrain, bb_int_t x, bb_int_t z, bb_float_t height, bb_int_t realtime);\n";
    header << "extern bb_int_t bbGetEntityType(bb_int_t entity);\n";
    header << "extern bb_int_t bbLoadTerrain(bb_string_t file, bb_int_t parent);\n";
    header << "extern bb_int_t bbCreateTerrain(bb_int_t gridSize, bb_int_t parent);\n";
    header << "extern void bbTerrainShading(bb_int_t terrain, bb_int_t enable);\n";
    header << "extern void bbTerrainDetail(bb_int_t terrain, bb_int_t detail, bb_int_t morph);\n";
    header << "extern bb_int_t bbCreateSurface(bb_int_t mesh, bb_int_t brush);\n";
    header << "extern void bbScaleMesh(bb_int_t mesh, bb_float_t x, bb_float_t y, bb_float_t z);\n";
    header << "extern void bbFitMesh(bb_int_t mesh, bb_float_t x, bb_float_t y, bb_float_t z, bb_float_t width, bb_float_t height, bb_float_t depth, bb_int_t uniform);\n";
    header << "extern bb_float_t bbMeshWidth(bb_int_t mesh);\n";
    header << "extern bb_float_t bbMeshHeight(bb_int_t mesh);\n";
    header << "extern bb_float_t bbMeshDepth(bb_int_t mesh);\n";
    header << "extern void bbFlipMesh(bb_int_t mesh);\n";
    header << "extern void bbLightMesh(bb_int_t mesh, bb_float_t r, bb_float_t g, bb_float_t b, bb_float_t range, bb_float_t lr, bb_float_t lg, bb_float_t lb);\n";
    header << "extern bb_int_t bbCreateMirror(bb_int_t parent);\n";
    header << "extern void bbChangeDir(bb_string_t dir);\n";
    header << "extern bb_int_t bbCreateListener(bb_int_t parent, bb_float_t rolloff, bb_float_t doppler, bb_float_t dist);\n";
    header << "extern void bbCaptureWorld(void);\n";
    header << "extern bb_int_t _bbStrToInt(bb_string_t s);\n";
    header << "\n";
    header << "/* MD2 Animation */\n";
    header << "extern bb_int_t bbLoadMD2(bb_string_t file, bb_int_t parent);\n";
    header << "extern void bbAnimateMD2(bb_int_t entity, bb_int_t mode, bb_float_t speed, bb_int_t firstFrame, bb_int_t lastFrame, bb_float_t transition);\n";
    header << "extern bb_float_t bbMD2AnimTime(bb_int_t entity);\n";
    header << "extern bb_int_t bbMD2AnimLength(bb_int_t entity);\n";
    header << "extern bb_int_t bbMD2Animating(bb_int_t entity);\n";
    header << "\n";
    header << "/* Joystick functions */\n";
    header << "extern bb_int_t bbJoyXDir(bb_int_t port);\n";
    header << "extern bb_int_t bbJoyYDir(bb_int_t port);\n";
    header << "extern bb_int_t bbJoyDown(bb_int_t button, bb_int_t port);\n";
    header << "extern bb_int_t bbJoyHit(bb_int_t button, bb_int_t port);\n";
    header << "extern bb_float_t bbJoyX(bb_int_t port);\n";
    header << "extern bb_float_t bbJoyY(bb_int_t port);\n";
    header << "extern bb_float_t bbJoyZ(bb_int_t port);\n";
    header << "\n";
    header << "/* Terrain functions */\n";
    header << "extern bb_int_t bbTerrainSize(bb_int_t terrain);\n";
    header << "\n";
    header << "/* Input functions */\n";
    header << "extern bb_string_t bbInput(bb_string_t prompt);\n";
    header << "\n";
    header << "/* Timer functions */\n";
    header << "extern bb_int_t bbCreateTimer(bb_int_t hertz);\n";
    header << "extern bb_int_t bbWaitTimer(bb_int_t timer);\n";
    header << "extern void bbFreeTimer(bb_int_t timer);\n";
    header << "\n";
    header << "/* Mesh functions */\n";
    header << "extern void bbRotateMesh(bb_int_t mesh, bb_float_t pitch, bb_float_t yaw, bb_float_t roll);\n";
    header << "extern void bbPositionMesh(bb_int_t mesh, bb_float_t x, bb_float_t y, bb_float_t z);\n";
    header << "\n";
    header << "/* Buffer functions */\n";
    header << "extern void bbSaveBuffer(bb_int_t buffer, bb_string_t filename);\n";
    header << "\n";
}

Codegen_C::~Codegen_C() {
}

void Codegen_C::SetTarget(const Target &t) {
    target = t.type;
}

void Codegen_C::indent() {
    indentLevel++;
}

void Codegen_C::outdent() {
    if (indentLevel > 0) indentLevel--;
}

void Codegen_C::emit(const std::string &code) {
    *current << code;
}

void Codegen_C::emitLine(const std::string &code) {
    for (int i = 0; i < indentLevel; i++) {
        *current << "    ";
    }
    *current << code << "\n";
}

void Codegen_C::emitLabel(const std::string &label) {
    *current << label << ":;\n";
}

void Codegen_C::emitGlobal(const std::string &code) {
    globals << code << "\n";
}

std::string Codegen_C::toCType(Type *type) {
    if( type == Type::int_type ) return "bb_int_t";
    if( type == Type::float_type ) return "bb_float_t";
    if( type == Type::string_type ) return "bb_string_t";
    if( type->structType() ) return "bb_obj_t";
    // Default to bb_int_t for unknown types
    return "bb_int_t";
}

std::string Codegen_C::toCSafeName(const std::string &name) {
    std::string result = name;
    // Replace characters that aren't valid in C identifiers
    for (size_t i = 0; i < result.size(); i++) {
        char c = result[i];
        if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
              (c >= '0' && c <= '9' && i > 0) || c == '_')) {
            result[i] = '_';
        }
    }
    // Prefix with bb_ to avoid conflicts with C keywords
    return "bb_" + result;
}

std::string Codegen_C::constantInt(int i) {
    return std::to_string(i) + "LL";
}

std::string Codegen_C::constantFloat(double f) {
    std::stringstream ss;
    ss.precision(17);
    ss << std::fixed << f;
    return ss.str();
}

std::string Codegen_C::constantString(const std::string &s) {
    auto it = strings.find(s);
    if (it != strings.end()) {
        return it->second;
    }

    std::string name = "_str" + std::to_string(stringCounter++);
    strings[s] = name;

    // Emit string constant in globals
    globals << "static const char " << name << "[] = \"";
    for (char c : s) {
        if (c == '"') globals << "\\\"";
        else if (c == '\\') globals << "\\\\";
        else if (c == '\n') globals << "\\n";
        else if (c == '\r') globals << "\\r";
        else if (c == '\t') globals << "\\t";
        else globals << c;
    }
    globals << "\";\n";

    return name;
}

std::string Codegen_C::newTemp() {
    return "_tmp" + std::to_string(tempCounter++);
}

std::string Codegen_C::getLabel(const std::string &ident) {
    std::string label = "_L" + toCSafeName(ident) + "_" + std::to_string(labelCounter++);
    return label;
}

void Codegen_C::declareLocal(const std::string &name, const std::string &cType) {
    if (localVars.find(name) == localVars.end()) {
        localVars[name] = cType;
    }
}

void Codegen_C::declareArray(const std::string &ident, int dims) {
    arrays[ident] = dims;
    // TODO: emit array declaration
}

void Codegen_C::beginMain() {
    current = &mainCode;
    emitLine("void bbMain(void) {");
    indent();
}

void Codegen_C::endMain() {
    outdent();
    emitLine("}");
}

void Codegen_C::beginFunction(const std::string &name, const std::string &returnType,
                               const std::vector<std::pair<std::string, std::string>> &params) {
    current = &functions;

    std::stringstream sig;
    sig << returnType << " " << toCSafeName(name) << "(";
    for (size_t i = 0; i < params.size(); i++) {
        if (i > 0) sig << ", ";
        sig << params[i].first << " " << params[i].second;
    }
    sig << ") {";

    emitLine(sig.str());
    indent();
}

void Codegen_C::endFunction() {
    outdent();
    emitLine("}");
    emitLine("");
    current = &mainCode;
}

std::string Codegen_C::callRuntime(const std::string &func, const std::vector<std::string> &args) {
    std::stringstream ss;
    ss << func << "(";
    for (size_t i = 0; i < args.size(); i++) {
        if (i > 0) ss << ", ";
        ss << args[i];
    }
    ss << ")";
    return ss.str();
}

std::string Codegen_C::generateOutput() {
    std::stringstream output;

    output << header.str();
    output << "\n/* Global variables */\n";
    output << globals.str();
    output << "\n/* Data section */\n";
    output << "static bb_int_t bbData[] = {";
    for (size_t i = 0; i < dataValues.size(); i++) {
        if (i > 0) output << ", ";
        output << dataValues[i];
    }
    if (dataValues.empty()) output << "0";
    output << "};\n";
    output << "\n/* Functions */\n";
    output << functions.str();
    output << "\n/* Main program */\n";
    output << mainCode.str();
    output << "\n/* Entry point */\n";
    output << "int main(int argc, char **argv) {\n";
    output << "    bbStart(argc, argv, bbMain, " << (debug ? "1" : "0") << ");\n";
    output << "    return 0;\n";
    output << "}\n";

    return output.str();
}

int Codegen_C::compileToObject(const std::string &outputPath) {
    // Write C code to temporary file
    std::string cFile = outputPath + ".c";
    std::ofstream out(cFile);
    if (!out) {
        std::cerr << "Error: Cannot create " << cFile << std::endl;
        return 1;
    }
    out << generateOutput();
    out.close();

    // Compile with gcc/clang
    std::string compiler = "gcc";
#ifdef __APPLE__
    compiler = "clang";
#endif

    std::string cmd = compiler + " -c -O2 -o " + outputPath + " " + cFile;
    int ret = system(cmd.c_str());

    if (ret == 0) {
        // Clean up C file on success (optional, keep for debugging)
        // remove(cFile.c_str());
    }

    return ret;
}
